version: '2'
services:

  mongo:
    container_name: mongo
    image: mongo:3.2.6
    network_mode: host
    restart: always
    ports:
      - "27017:27017"
    command: [mongod, --smallfiles]
  
  redis:
    container_name: redis
    image: "redis:3.2-alpine"
    network_mode: host
    restart: always
    ports:
      - '6379:6379'
  
  app_api:
    container_name: app_api
    image: app_api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    network_mode: host

  